dataset:
  # Relative to workspace
  path: !path "3_processed/MLO_Obs_Stacked.csv.gz"
  test_interval:
    - 2006-07-01
    - 2006-07-15
  # If columns in data file are named differently than in vars.yml, map them here
  col_to_var:
    u_u: var_u
    tc_tc: var_theta
    w_tc: shfx
    theta_K: theta

flaml:
  estimator_list:
    - "xgboost"
  time_budget: 120  # in seconds
  metric: "rmse"

  # Technical settings
  n_jobs: 8
  verbose: 3
  seed: 0  # Important for reproducibility

n_members: 15